stages:
  - aquilax
  
Security Scan:
  stage: aquilax
  variables:
    AQUILAX_ORG_ID: "6971641266e58de7aff48cb9"
    AQUILAX_GROUP_ID: "6998284f4fb2909c8f60d446"
  image: python:3.12-slim
  allow_failure: true
  timeout: 5m
  script:
    - |
      echo "$CI_PROJECT_URL.git" - "$CI_COMMIT_REF_NAME"
      pip3 install --no-cache-dir --upgrade aquilax
      aquilax -v
      aquilax login "$AQUILAX_API_TOKEN" --server "https://aquilax.ai" || exit 1
      aquilax ci-scan \
        "$CI_PROJECT_URL".git \
        --org-id "$AQUILAX_ORG_ID" \
        --group-id "$AQUILAX_GROUP_ID" \
        --branch "$CI_COMMIT_REF_NAME"
  artifacts:
    when: always 
    paths:
      - results.sarif
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
