version: "3.9"

services:
  airgapmanager-dev:
    image: node:20-alpine      # Use Node image directly, no Dockerfile
    working_dir: /app
    volumes:
      - ./frontend/airgap/airgapmanager:/app   # Mount project source code
      - /app/node_modules                      # Keep node_modules inside container
    ports:
      - "5173:5173"           # host:container (Vite default port is 5173)
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    container_name: airgapmanager-dev
    networks:
      - airgap-network
    depends_on:
      - airgap-service

  postgres:
    image: postgres:15
    container_name: airgap-postgres
    environment:
      POSTGRES_DB: airgap_dev_db
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - db_user
      - db_password

    ports:
      - "5433:5432"
    volumes:
      - airgap_pgdata:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/db_user) -d airgap_dev_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - airgap-network

  airgap-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: airgap-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/airgap_db
      SPRING_DATASOURCE_USERNAME: airgap_user
      SPRING_DATASOURCE_PASSWORD: airgap_pass
      SPRING_PROFILES_ACTIVE: docker
      AIRGAP_AES_KEY: ${AIRGAP_AES_KEY}

    volumes:
      - ./config/config.json:/opt/airgap/config/config.json
      - ./data/collection/in:/opt/airgap/data/collect/in
      - ./upstream/data:/opt/airgap/data/upstream
      - ./downstream/data:/opt/airgap/data/downstream

    restart: always

    networks:
      - airgap-network

volumes:
  airgap_pgdata:

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

networks:
  airgap-network:
    driver: bridge