version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: airgap-postgres
    environment:
      POSTGRES_DB: airgap_db
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    ports:
      - "5433:5432"
    volumes:
      - airgap_pgdata:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/db_user) -d airgap_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - airgap-network

  airgap-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: airgap-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/airgap_db
      SPRING_DATASOURCE_USERNAME: airgap_user
      SPRING_DATASOURCE_PASSWORD: airgap_pass
      SPRING_PROFILES_ACTIVE: docker
      AIRGAP_AES_KEY: ${AIRGAP_AES_KEY}
    volumes:
      - ./config:/opt/airgap/config/config.json
      - ./downstream/data/collection/in:/opt/airgap/downstream/data/collection/in
      - ./downstream/data/package_output:/opt/airgap/downstream/data/package_output
      - ./upstream/data/package_input:/opt/airgap/upstream/data/package_input
      - ./upstream/data/upload_output:/opt/airgap/upstream/data/upload_output
    restart: always
    networks:
      - airgap-network

volumes:
  airgap_pgdata:

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

networks:
  airgap-network:
    driver: bridge