# ===============================
# Server
# ===============================
server.port=8081
spring.application.name=airgap-service

# ===============================
# JSON only via Gson
# ===============================
spring.mvc.converters.preferred-json-mapper=gson

# ===============================
# Datasource (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/airgap_dev_db
spring.datasource.username=airgap_dev_user
spring.datasource.password=airgap_dev_pass
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.default_schema=airgap

# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Airgap Paths (use @Value in code)
# ===============================

# root in files message
#airgap.collect.in=/COLLECTED_DATA/IN
# root out files message
#airgap.collect.out=/COLLECTED_DATA/OUT

#test env properties
airgap.collect.in =target/test/IN
airgap.collect.out=target/test/OUT

# directory after the package are created successfuly
#airgap.incoming.packages.dir=/COLLECTED_DATA/IN_PACKAGES
#test direction after package is created
airgap.incoming.packages.dir=target/test/PKG
# Archive for PKG_*.tar after import success. Just for work history or audit only.
airgap.incoming.packages.archive.dir=/COLLECTED_DATA/IN_PACKAGES_ARCHIVE
# Working directory for unzip (TEMP)
airgap.unpack.work.dir=/COLLECTED_DATA/WORK

#directory when the package will be uploaded
#airgap.uploaded.packages.dir=target/test/UPLOAD-PKG

airgap.uploaded.packages.dir=/COLLECTED_DATA/UPLOAD


# ===============================
# AUTO packaging (Quartz)
# ===============================
#airgap.auto.hours=1
#airgap.auto.size-check-interval-min=10
#airgap.auto.max-mb=100
#airgap.file.stable.seconds=20

# ===============================
# AUTO packaging (Quartz) for TEST
# ===============================
airgap.auto.hours=1
airgap.auto.size-check-interval-min=100
airgap.file.stable.seconds=100
airgap.auto.max-mb=1000


# ===============================
# Cleanup (Quartz)
# ===============================
airgap.cleanup.days=10

# ===============================
# Crypto
# AES-256 key (Base64) -> 32 bytes when decoded
# ===============================
airgap.crypto.aes256.key.base64=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

