# ===============================
# Server
# ===============================
server.port=8083
spring.application.name=airgap-service
server.servlet.context-path=/airgapservice

logging.level.org.apache.catalina.connector=DEBUG
logging.level.org.apache.tomcat.util.http.fileupload=DEBUG

server.tomcat.max-swallow-size=-1
server.tomcat.connection-timeout=3600000
spring.mvc.async.request-timeout=3600000
# ===============================
# JSON only via Gson
# ===============================
spring.mvc.converters.preferred-json-mapper=gson

# ===============================
# Datasource (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/airgap_dev_db
spring.datasource.username=airgap_dev_user
spring.datasource.password=airgap_dev_pass
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.default_schema=airgap


# ===============================
# Airgap Paths (LOCAL)
# ===============================

airgap.collect.in =target/test/IN
airgap.save.original.packages.dir=target/test/ORIGINAL-PKG
airgap.collect.out=target/test/OUT
airgap.archive.packages.dir=target/test/ARCHIVE
airgap.unpack.work.dir=target/test/WORK
airgap.uploaded.packages.dir=target/test/UPLOAD-PKG

# ===============================
# AUTO packaging (Quartz)
# ===============================
airgap.auto.hours=1
airgap.auto.size-check-interval-min=10
airgap.auto.max-mb=100
airgap.file.stable.seconds=20

# ===============================
# AUTO packaging (Quartz) for TEST
# ===============================
#airgap.auto.hours=1
#airgap.auto.size-check-interval-min=1
#airgap.file.stable.seconds=10
#airgap.auto.max-mb=1


# ===============================
# Cleanup (Quartz)
# ===============================
airgap.cleanup.enabled=true
airgap.cleanup.archive.days=1
airgap.collect.rescan-ms=30000

# Quartz trigger (once per day, at 02:00 AM)
airgap.cleanup.cron=0 0 2 * * ?

#every 2 min
#airgap.cleanup.cron=0 */2 * * * ?


# ===============================
# Crypto
# AES-256 key (Base64) -> 32 bytes when decoded
# ===============================
airgap.crypto.aes256.key.base64=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=


# ===============================
# Airgap Paths (CONTAINER)
# ===============================

#airgap.collect.in=/opt/airgap/data/collect/in
#airgap.collect.out=/opt/airgap/data/collect/out
#airgap.save.original.packages.dir=/opt/airgap/data/original-packages
#airgap.archive.packages.dir=/opt/airgap/data/incoming/archive
#airgap.unpack.work.dir=/opt/airgap/data/work
#airgap.uploaded.packages.dir=/opt/airgap/data/upload

# ===============================
# File Config Paths (CONTAINER / LOCAL)
# ===============================
#airgap.config.path=/opt/airgap/config/config.json
airgap.config.path=/Users/user/IdeaProjects/config/config.json