# ===============================
# Server
# ===============================
server.port=8081
spring.application.name=airgap-service

# ===============================
# JSON only via Gson
# ===============================
spring.mvc.converters.preferred-json-mapper=gson

# ===============================
# Datasource (PostgreSQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/airgap_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=airgap

# ===============================
# Ftp credentials
# ===============================
airgap.ftp.port=21
airgap.ftp.passive-mode=true

# ===============================
# AUTO packaging (Quartz)
# ===============================
airgap.auto.hours=1
airgap.auto.size-check-interval-min=10
airgap.auto.max-mb=100
airgap.file.stable.seconds=20

# ===============================
# Cleanup (Quartz)
# ===============================
airgap.cleanup.enabled=true
airgap.cleanup.archive.days=1
airgap.collect.rescan-ms=30000

# Quartz trigger (once per day, at 02:00 AM)
airgap.cleanup.cron=0 0 2 * * ?

# ===============================
# Crypto
# AES-256 key (Base64) -> 32 bytes when decoded
# ===============================
airgap.crypto.aes256.key.base64=${AIRGAP_AES_KEY}

# ===============================
# Airgap Paths (CONTAINER)
# ===============================
airgap.collect.in=/opt/airgap/downstream/data/collection/in
airgap.collect.out=/opt/airgap/runtime/upstream/collection/out
airgap.save.original.packages.dir=/opt/airgap/runtime/downstream/original-packages
airgap.archive.packages.dir=/opt/airgap/runtime/upstream/archive
airgap.unpack.work.dir=/opt/airgap/runtime/upstream/work
airgap.uploaded.packages.dir=/opt/airgap/upstream/data/package_input

# ===============================
# File Config Paths (OUTSIDE CONTAINER / LOCAL)
# ===============================
airgap.config.path=/opt/airgap/config/config.json